---
apiVersion: v1
kind: Service
metadata:
  name: gerundium-brand-voting-app
  labels:
    app: gerundium-brand-voting-app
spec:
  selector:
    app: gerundium-brand-voting-app
  ports:
  - name: "web"
    port: 8501
    targetPort: 8501
    protocol: TCP
  type: ClusterIP
