apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base
- ingress.yaml
namespace: prod
commonAnnotations:
  supported-by: sre@example.com
labels:
- includeSelectors: false
  pairs:
    project: gerundium-brand-voting-app
patches:
- path: service.yaml
- path: preview-service.yaml
- path: patch-rollout-strategy.yaml
- path: patch-rollout-image.yaml
