---
apiVersion: v1
kind: Service
metadata:
  name: gerundium-brand-voting-app-preview
  labels:
    role: gerundium-brand-voting-app
spec:
  selector:
    app: gerundium-brand-voting-app
  ports:
    - port: 8501
      targetPort: 8501
      protocol: TCP
      nodePort: 30002
  type: NodePort